services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: flask_db
      MYSQL_PASSWORD: admin123
    ports:
      - 3307:3306
    volumes:
      - ./flask_db:/var/lib/mysql
